image: node:15

services:
  - mongo:latest

stages:
  - build
  - deploy

cache:
  paths:
    - node_modules/

build:
  stage: build
  script:
    - npm install

deploy:
  stage: deploy
  environment: production
  script:
    - 'git checkout master'
    - 'eb deploy $AWS_EB_ENVIRONMENT'
  only:
    - master
